apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawreef-6-pvc
  namespace: clawmanager-user-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem