apiVersion: v1
kind: Service
metadata:
  labels:
    app: clawreef
    instance-id: "6"
    instance-name: test
    managed-by: clawreef
    user-id: "1"
  name: clawreef-6-test-svc
  namespace: clawmanager-user-1
spec:
  clusterIP: 10.43.155.97
  clusterIPs:
  - 10.43.155.97
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: clawreef
    instance-id: "6"
  sessionAffinity: None
  type: ClusterIP